# Generated by Django 3.0.4 on 2020-09-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200902_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='url_name',
            field=models.CharField(default='', editable=False, max_length=80, verbose_name='url name'),
        ),
    ]
