# Generated by Django 3.0.4 on 2020-09-08 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200906_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='url_name',
            field=models.CharField(editable=False, max_length=80, verbose_name='url name'),
        ),
    ]
