# Generated by Django 3.0.4 on 2020-09-27 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200908_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='url_name',
        ),
    ]
