# Generated by Django 3.0.4 on 2020-08-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200601_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='default_pp.png', upload_to='profile_pictures'),
        ),
    ]
