# Generated by Django 3.0.4 on 2020-08-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_dislikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='default_tb.png', upload_to='post_thumbnails'),
        ),
    ]
