# Generated by Django 3.0.4 on 2020-08-27 17:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200827_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='date_updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', related_query_name='post', to='blog.Category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('GN', 'General'), ('TY', 'Technology'), ('LS', 'Lifestyle'), ('FN', 'Fashion'), ('BS', 'Business'), ('FA', 'Family'), ('ET', 'Entertainment'), ('PO', 'Politics'), ('SE', 'Seo'), ('GG', 'Gaming'), ('MU', 'Music')], default='GN', max_length=25),
        ),
    ]
