# Generated by Django 3.0.4 on 2020-08-28 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200828_0010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_published']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date_posted',
            new_name='date_created',
        ),
        migrations.AddField(
            model_name='post',
            name='date_published',
            field=models.DateField(blank=True, null=True),
        ),
    ]
