# Generated by Django 3.0.4 on 2020-08-29 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200828_2157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_created']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='date_posted',
            new_name='date_created',
        ),
    ]
