# Generated by Django 3.0.4 on 2020-09-28 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0005_auto_20200928_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='display_name',
        ),
    ]
